<div>
	<img width="180" height="53" src="https://trello-attachments.s3.amazonaws.com/553fd41703690c3652c38f3f/180x53/ef9a829a6a65dbd662595c2bff168735/logo.png" />
	<br /><br />
    <h4>
       Shiptheory. Making Ship Simple.
    </h4>
    <p>
        Need help using the Shiptheory extension? Read our <a href="http://support.shiptheory.com/solution/articles/6000004521-getting-started-with-magento-and-your-carrier" target="_blank">getting started guide</a>
    </p>
    <br />
</div>
